apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  {{ .Values.twi.prefix }}-twi-bookmark-api
  name:  {{ .Values.twi.prefix }}-twi-bookmark-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.twi.prefix }}-twi-bookmark-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum  }}
      labels:
        app:  {{ .Values.twi.prefix }}-twi-bookmark-api
    spec:
      containers:

          env:
            - name: SERVER_PORT
              value: 8080

        - envFrom:
            - configMapRef:
                name:  {{ .Values.twi.prefix }}-twi-configmap
          image: gcr.io/pgtm-jlong/twi-bookmark-api
          imagePullPolicy: Always
          name:   {{ .Values.twi.prefix }}-twi-bookmark-api
          readinessProbe:
            failureThreshold: 240
            periodSeconds: 240
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            failureThreshold: 240
            periodSeconds: 240            
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
---
apiVersion:  v1 
kind:  Service 
metadata:
  name:  {{ .Values.twi.prefix }}-twi-bookmark-api-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app:  {{ .Values.twi.prefix }}-twi-bookmark-api
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    networking.gke.io/managed-certificates: "{{ .Values.twi.prefix }}-twi-bookmark-api-certificate"
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.twi.prefix }}-twi-bookmark-api-ip"
  name: {{ .Values.twi.prefix }}-twi-bookmark-api-ingress
spec:
  defaultBackend:
    service:
      name: {{ .Values.twi.prefix }}-twi-bookmark-api-service
      port:
        number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.twi.prefix }}-twi-bookmark-api-certificate
spec:
  domains:
    - bookmark-api.{{ .Values.twi.domain }}