apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  {{ .Values.twi.prefix }}-twi-studio-gateway
  name:  {{ .Values.twi.prefix }}-twi-studio-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.twi.prefix }}-twi-studio-gateway
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum  }}
      labels:
        app:  {{ .Values.twi.prefix }}-twi-studio-gateway
    spec:
      containers:

        - envFrom:
            - configMapRef:
                name:  {{ .Values.twi.prefix }}-twi-configmap
          image: gcr.io/pgtm-jlong/twi-studio-gateway
          env:
            
            - name: "TWI_GATEWAY_STUDIO_CLIENT_URI"
              value: https://studio-client.{{ .Values.twi.domain }}
            
            - name: "TWI_GATEWAY_BOOKMARKS_API_URI"
              value: https://bookmark-api.{{ .Values.twi.domain }}
            
            - name: "SERVER_PORT"
              value: "8080"

          imagePullPolicy: Always
          name:   {{ .Values.twi.prefix }}-twi-studio-gateway
          readinessProbe:
            failureThreshold: 240
            periodSeconds: 240
            httpGet:
              port: 8080
              path: /actuator/health/readiness
          livenessProbe:
            failureThreshold: 240
            periodSeconds: 240            
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"

---
apiVersion: v1 
kind: Service 
metadata:
  name: {{ .Values.twi.prefix }}-twi-studio-gateway-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app:  {{ .Values.twi.prefix }}-twi-studio-gateway
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    networking.gke.io/managed-certificates: "{{ .Values.twi.prefix }}-twi-studio-gateway-certificate"
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.twi.prefix }}-twi-studio-gateway-ip"
  name:  {{ .Values.twi.prefix }}-twi-studio-gateway-ingress
spec:
  defaultBackend:
    service:
      name: {{ .Values.twi.prefix }}-twi-studio-gateway-service
      port:
        number: 80              
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name:  {{ .Values.twi.prefix }}-twi-studio-gateway-certificate
spec:
  domains:
    - studio.{{ .Values.twi.domain }}