---
apiVersion:  batch/v1
kind: CronJob
metadata:
  name:  {{ .Values.twi.prefix }}-twi-twitter-ingest-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum  }}

        spec:
          containers:
            - name:  {{ .Values.twi.prefix }}-twitter-ingest-cronjob-container 
              image: gcr.io/pgtm-jlong/twi-twitter-ingest-job:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name:  {{ .Values.twi.prefix }}-twi-configmap
          restartPolicy: OnFailure
