name: Helm Charts

# env:
#   GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
#   GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE }}
#   NS_NAME: ${{ secrets.NS_NAME }}
#   GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Deploy
        run: cd $GITHUB_WORKSPACE/.github/workflows/ && ./deploy.sh