name: Helm Charts

env:
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GCLOUD_ZONE: ${{ secrets.GCLOUD_ZONE }}
  NS_NAME: ${{ secrets.NS_NAME }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GCLOUD_ZONE }}'

      - run: |
          gcloud config set project $GCLOUD_PROJECT 
          gcloud --quiet auth configure-docker
          kubectl get pods

      - name: Deploy
        run: cd $GITHUB_WORKSPACE/.github/workflows/ && ./deploy.sh